# Generated by Django 4.0.5 on 2022-06-17 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='inventary_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='computer',
            name='serial_number',
            field=models.IntegerField(),
        ),
    ]
